<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <PublishDir>$(MSBuildProjectDirectory)\..\..\publish\</PublishDir>
    <AssemblyName>LEDapp-2.0</AssemblyName>
    <AssemblyTitle>LEDapp-2.0</AssemblyTitle>
    <Product>LEDapp-2.0</Product>
    <ApplicationTitle>LEDapp-2.0</ApplicationTitle>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>Assets\logo.ico</ApplicationIcon>
    <UsedAvaloniaProducts></UsedAvaloniaProducts>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.10" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="11.3.10" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.10" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.10" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.10" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.10">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LedController.Core\LedController.Core.csproj" />
    <ProjectReference Include="..\LedController.Infrastructure\LedController.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\trayicon.png" />
    <AvaloniaResource Include="Assets\logo.ico" />
  </ItemGroup>
</Project>
