<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LedController.Core\LedController.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="InTheHand.BluetoothLE" Version="4.0.44" />
    <PackageReference Include="MQTTnet" Version="4.3.7.1207" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="Linux.Bluetooth" Version="5.67.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFrameworks>net8.0;net8.0-windows10.0.19041.0</TargetFrameworks>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' != 'net8.0-windows10.0.19041.0'">
    <Compile Remove="Services\BleService.cs" />
    <Compile Remove="Services\StartupService.cs" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-windows10.0.19041.0'">
    <Compile Remove="Services\LinuxBleService.cs" />
    <Compile Remove="Services\LinuxStartupService.cs" />
  </ItemGroup>

</Project>
